spring.application.name=gestionsachat

# ── Database (PostgreSQL in Docker) ──────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionsachat
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver

# ── Docker Compose Support ──────────────────────────
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop


# ── JPA ─────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# ── Server ──────────────────────────────────────────
server.port=8080