package com.pfe.gestionsachat.model;

public enum StatutDA {
    EN_ATTENTE_N1,
    EN_ATTENTE_N2,
    EN_ATTENTE_TECH,
    EN_ATTENTE_ACHAT,
    EN_ATTENTE_AMG,
    EN_ATTENTE_DAF,
    EN_ATTENTE_DG,
    EN_AJUSTEMENT,
    EN_ATTENTE_AJUSTEMENT_DAF,
    EN_ATTENTE_AJUSTEMENT_DG,
    EN_ATTENTE_PO,
    VALIDEE,
    PO_CREE,
    REJETEE
}
